// Auto-generated by: supabase gen types typescript --linked > types/database.types.ts
// STUB temporário — substituir após: supabase db push

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

type Relationship = {
  foreignKeyName: string
  columns: string[]
  isOneToOne?: boolean
  referencedRelation: string
  referencedColumns: string[]
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyRow = Record<string, any>

type AnyTable = {
  Row: AnyRow
  Insert: AnyRow
  Update: AnyRow
  Relationships: Relationship[]
}

export interface Database {
  public: {
    Tables: {
      user_settings: AnyTable
      user_marketing_context: AnyTable
      user_goals: AnyTable
      pipeline_stages: AnyTable
      leads_qualified: AnyTable
      leads_instagram: AnyTable
      leads_raw: AnyTable
      scraping_jobs: AnyTable
      content_ideas: AnyTable
      content_calendar: AnyTable
      instagram_posts: AnyTable
      instagram_comments: AnyTable
      chat_conversations: AnyTable
      chat_messages: AnyTable
      chat_usage_logs: AnyTable
      notifications: AnyTable
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
